In [2]:
import numpy as np

#1. Create a null vector of size 10 but the fifth value which is 1.

vector=np.zeros(10)
vector[4]=1
vector



array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2.Create a vector with values ranging from 10 to 49.

x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#3.Create a 3x3 matrix with values ranging from 0 to 8

matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

a=np.array([1,2,0,0,4,0])
print(a.nonzero())


(array([0, 1, 4], dtype=int64),)


In [24]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
mat=np.random.randint(1,1000,(10,10))
print(mat)
print(mat.max())
print(mat.min())

[[204 917 230 439 177 952 471 117 754 290]
 [107 289 499 818 905 245 265  57 463 371]
 [483 956 485 215 425   3 673 118 147 116]
 [ 56 694 506 944 956 684 832 836 109 680]
 [385 421 734 618 567 259 722 211  83 681]
 [862 171 529 573 150 255 245 700 615 552]
 [275 663 869 457  12 952  93 673 664 706]
 [258 620 400  30 499 852 288 321 442 738]
 [120 517 477 924 516 113 248 831 354 966]
 [114 790 122 108 634 257 688 626 800 868]]
966
3


In [33]:
#6. Create a random vector of size 30 and find the mean value.
x=np.random.randint(0,100,(3,10))
print(x)
print(x.mean())

[[36 99 77 60 63 12 91  6 60 95]
 [64 48 10 66 22 15 11 41 93 59]
 [17 25 24 70 85  4 25 35 50 50]]
47.1
